/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limasky_test_LSGL2Renderer */

#ifndef _Included_com_limasky_test_LSGL2Renderer
#define _Included_com_limasky_test_LSGL2Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limasky_test_LSGL2Renderer
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_limasky_test_LSGL1Renderer_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_limasky_test_LSGL2Renderer
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_limasky_test_LSGL1Renderer_step
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
