/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limasky_test_MessageHandler */

#ifndef _Included_com_limasky_test_MessageHandler
#define _Included_com_limasky_test_MessageHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limasky_test_MessageHandler
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_limasky_test_MessageHandler_initNative
  (JNIEnv *, jobject);

/*
 * Class:     com_limasky_test_MessageHandler
 * Method:    destroyNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_limasky_test_MessageHandler_destroyNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
